
# Data Management Toolbox

Data Management toolbox in ArcGIS pro provides the users a variety of tools for managing,
maintaining and developing datasets that come in all possible forms (feature classes / datasets, raster datasets). It consists of 32 toolsets as listed below. Many of the toolsets are rarely used, we will focus on the most commonly used tools. 


- [ ] 3D Objects
- [ ] Archiving
- [ ] Attachments
- [ ] Attribute Rules
- [ ] Contingent Values
- [ ] Data Comparison
- [ ] Distributed Geodatabase
- [ ] Domains
- [ ] Feature Binning
- [ ] Feature Class
- [ ] Features
- [ ] Fields
- [ ] File Geodatabase
- [ ] General
- [ ] Generalization
- [ ] Geodatabase Administration
- [ ] Indexes
- [x] Joins and Relates
- [ ] LAS Dataset
- [ ] Layers and Table Views
- [ ] Package
- [ ] Photos
- [x] Projections and Transformations
- [ ] Raster
- [ ] Relationship Classes
- [ ] Sampling
- [ ] Subtypes
- [ ] Table
- [ ] Tile Cache
- [ ] Topology
- [ ] Versions
- [ ] Workspace




<!-- ### Raster Properties Toolset -->
