# Data

```{r, include=FALSE}
source("R/before_chapter.R", local = knitr::knit_global())
```

As an ArcGIS user, you are probably very familiar with the two major geodata formats, raster data and vector data. In the case of vector data, we typically use *shapefiles* and geodatabases with *feature classes*. For raster data, we use *geotiff* or *ESRI GRID* files inside geodatabases. As you work with OpenSource GIS Tools and Data, you will come across a much richer ecosystem of data formats. 

//todo add some examples of geodata-formats (gpkg, sqlite)
//body link to switchfromshapefile.org



In ArcGIS, you add a new dataset to your project using the "Add Data" button in the "Map" Pane. ArcGIS then "helps" you in various ways that `R` will not. For example, ArcGIS:

- ... only displays files with extensions that can contain geodata (e.g. `.tif`, `.shp` etc)
- ... recognizes files that come in a multifile format with a common prefix (e.g. shapefiles) and displays it as a single dataset
- ... let's you visually examine the content of .gdb-files
- ... displays the datatype / geometrytype of a dataset as a little icon
- ... automatically uses the correct mechanisms to import a dataset  <!-- (so you dont have to care whether it is raster, vector, multiband or singleband format) -->

`R` provides less help when importing a dataset which can be seen as a disadvantage, but in many cases is much more preferable. `R` *interferes less* and *assumes an informed user* who has good knowledge of the data. Just like when importing datasets using `read.csv`, `read.delim` and so on, you need to prior knowledge of your data to import it correctly: You need to know the delimiter used to separate columns, and the encoding used to store the information. 

<!-- Similar, importing geodata into R requires specific functions depending on the dataset, and sometimes specific arguments depending on the characteristics of you dataset.  -->

The same holds true when importing geodata in R: depending on the *type* of geodata, we need different packages to handle the data and different functions to import it. For handling vector data, the package `sf` now has replaced its predecessor `sp`. `sf` is so powerful and simple, that it has helped bring GIS workflows to non-GIS R users. For handling raster data, the package `raster` is still in heavy use but is in the process of being replaced by it's successor, `terra`.