on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Install gdal
        run: |
          brew install gdal 

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_deps()'
          R -e 'remotes::install_github("arc2r/arc2r",dependencies = TRUE, upgrade = "always")'

      - name: Build book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Push output to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /docs
          
      - name: Build readme
        run: |
          R -e 'rmarkdown::render("Readme.Rmd","github_document",output_file = "Readme.md")'

      - name: Commit readme
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "update Readme"
          
      - name: Push changes to readme
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}