on:
  push:
    branches:
      - main
      - master

name: Generate templates

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Build template files
        run: |
          source('R/build_template_files.R')
        shell: Rscript {0} 

      - name: Pushes to another repository  
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'template_rmds'
          destination-github-username: 'ratnanil'
          destination-repository-name: 'templatefiles'
          destination-repository-username: 'arc2r'
          user-email: 'rata@zhaw.ch'
          commit-message: 'updated template files'